#server
server:
  port: 9090
  #ssl:
    #key-store: .keystore
    #key-alias: tomcat
    #key-password: 123456
    #key-store-type: JKS
#  tomcat:
#    uri-encoding:UTF-8


#loggin
logging:
    level: 
      com.alibaba: debug
  
    




#spring
spring:
  #mysql-jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/itemdemo?characterEncoding=UTF-8
    username: itemdemo
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #redis
  redis:
      host: localhost
      port: 6379
      default_expire_time: 86400
      
  #jpa
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect